INSERT INTO user (create_date, email, grant_type, nick_name, password, user_id) VALUES 
('2024-03-04 12:00:00.000000', 'user1@example.com', 'NORMAL', 'user1', 'password1', 'testuserid1'),
('2024-03-04 12:00:00.000000', 'user2@example.com', 'NORMAL', 'user2', 'password2', 'testuserid2'),
('2024-03-04 12:00:00.000000', 'user3@example.com', 'NORMAL', 'user3', 'password1', 'testuserid3'),
('2024-03-04 12:00:00.000000', 'user4@example.com', 'NORMAL', 'user4', 'password2', 'testuserid4'),
('2024-03-04 12:00:00.000000', 'user5@example.com', 'NORMAL', 'user5', 'password5', 'testuserid5'),
('2024-03-04 12:00:00.000000', 'user6@example.com', 'ADMIN', 'admin1', 'adminpassword1', 'testadminid1'),
('2024-03-04 12:00:00.000000', 'user7@example.com', 'ADMIN', 'admin2', 'adminpassword2', 'testadminid2');

insert into recipe(servings, view, created_at, user_id, categorie, cook_method, description, recipe_name)
values
(1, 0, '2024-03-04 12:00:00.000000', (select id from user where user_id = 'testuserid1'), '한식', '굽기', '정말 맛있는 요리입니다!! 짱짱1', '테스트요리1'),
(2, 0, '2024-03-04 12:00:00.000000', (select id from user where user_id = 'testuserid1'), '한식', '굽기', '정말 맛있는 요리입니다!! 짱짱2', '테스트요리2'),
(2, 0, '2024-03-04 12:00:00.000000', (select id from user where user_id = 'testuserid1'), '한식', '굽기', '정말 맛있는 요리입니다!! 짱짱3', '테스트요리3'),
(2, 99, '2024-03-04 12:00:00.000000', (select id from user where user_id = 'testuserid1'), '양식', '굽기', '정말 맛있는 요리입니다!! 짱짱4', '테스트요리4'),
(2, 18, '2024-03-04 12:00:00.000000', (select id from user where user_id = 'testuserid2'), '양식', '튀기기', '정말 맛있는 요리입니다!! 짱짱5', '테스트요리5'),
(2, 100, '2024-03-10 12:00:00.000000', (select id from user where user_id = 'testuserid2'), '양식', '튀기기', '정말 맛있는 요리입니다!! 짱짱6', '테스트요리6'),
(2, 101, '2024-03-10 12:00:00.000000', (select id from user where user_id = 'testuserid2'), '중식', '튀기기', '정말 맛있는 요리입니다!! 짱짱7', '테스트요리7'),
(3, 199, '2024-03-10 12:00:00.000000', (select id from user where user_id = 'testuserid2'), '중식', '튀기기', '정말 맛있는 요리입니다!! 짱짱8', '테스트요리8'),
(3, 200, '2024-03-10 12:00:00.000000', (select id from user where user_id = 'testuserid2'), '중식', '삶기', '정말 맛있는 요리입니다!! 짱짱9', '테스트요리9'),
(4, 201, '2024-03-10 12:00:00.000000', (select id from user where user_id = 'testuserid3'), '일식', '삶기', '정말 맛있는 요리입니다!! 짱짱10', '테스트요리10'),
(4, 299, '2024-03-15 12:00:00.000000', (select id from user where user_id = 'testuserid3'), '일식', '삶기', '정말 맛있는 요리입니다!! 짱짱11', '테스트요리11'),
(4, 300, '2024-03-15 12:00:00.000000', (select id from user where user_id = 'testuserid3'), '일식', '삶기', '정말 맛있는 요리입니다!! 짱짱12', '테스트요리12'),
(5, 301, '2024-03-15 12:00:00.000000', (select id from user where user_id = 'testuserid3'), '일식', '삶기', '정말 맛있는 요리입니다!! 짱짱13', '테스트요리13'),
(5, 399, '2024-03-15 12:00:00.000000', (select id from user where user_id = 'testuserid3'), '후식', '삶기', '정말 맛있는 요리입니다!! 짱짱14', '테스트요리14'),
(5, 400, '2024-03-15 12:00:00.000000', (select id from user where user_id = 'testuserid4'), '후식', '삶기', '정말 맛있는 요리입니다!! 짱짱15', '테스트요리15'),
(5, 401, '2024-03-04 12:00:00.000000', (select id from user where user_id = 'testuserid4'), '건강식', '삶기', '정말 맛있는 요리입니다!! 짱짱16', '테스트요리16'),
(5, 499, '2024-03-04 12:00:00.000000', (select id from user where user_id = 'testuserid4'), '분식', '찌기', '정말 맛있는 요리입니다!! 짱짱17', '테스트요리17'),
(5, 500, '2024-03-04 12:00:00.000000', (select id from user where user_id = 'testuserid4'), '분식', '찌기', '정말 맛있는 요리입니다!! 짱짱18', '테스트요리18'),
(5, 501, '2024-03-04 12:00:00.000000', (select id from user where user_id = 'testuserid5'), '분식', '찌기', '정말 맛있는 요리입니다!! 짱짱19', '테스트요리19'),
(5, 1000, '2024-03-04 12:00:00.000000', (select id from user where user_id = 'testuserid5'), '분식', '볶기', '정말 맛있는 요리입니다!! 짱짱20', '테스트요리20');


insert into step(step_order, time, recipe_id, description)
values
(1, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리1%' limit 1), "요리1 단계 1번입니다."),
(2, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리1%' limit 1), "요리1 단계 2번입니다."),
(3, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리1%' limit 1), "요리1 단계 3번입니다."),
(1, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리2%' limit 1), "요리2 단계 2번입니다."),
(2, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리2%' limit 1), "요리2 단계 2번입니다."),
(3, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리2%' limit 1), "요리2 단계 3번입니다."),
(1, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리3%' limit 1), "요리3 단계 1번입니다."),
(2, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리3%' limit 1), "요리3 단계 2번입니다."),
(3, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리3%' limit 1), "요리3 단계 3번입니다."),
(1, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리4%' limit 1), "요리4 단계 2번입니다."),
(2, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리4%' limit 1), "요리4 단계 2번입니다."),
(3, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리4%' limit 1), "요리4 단계 3번입니다."),
(1, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리5%' limit 1), "요리5 단계 1번입니다."),
(2, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리5%' limit 1), "요리5 단계 2번입니다."),
(3, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리5%' limit 1), "요리5 단계 3번입니다."),
(1, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리6%' limit 1), "요리6 단계 2번입니다."),
(2, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리6%' limit 1), "요리6 단계 2번입니다."),
(3, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리6%' limit 1), "요리6 단계 3번입니다."),
(1, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리7%' limit 1), "요리7 단계 1번입니다."),
(2, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리7%' limit 1), "요리7 단계 2번입니다."),
(3, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리7%' limit 1), "요리7 단계 3번입니다."),
(1, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리8%' limit 1), "요리8 단계 2번입니다."),
(2, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리8%' limit 1), "요리8 단계 2번입니다."),
(3, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리8%' limit 1), "요리8 단계 3번입니다."),
(1, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리9%' limit 1), "요리9 단계 1번입니다."),
(2, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리9%' limit 1), "요리9 단계 2번입니다."),
(3, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리9%' limit 1), "요리9 단계 3번입니다."),
(1, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리10%' limit 1), "요리10 단계 2번입니다."),
(2, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리10%' limit 1), "요리10 단계 2번입니다."),
(3, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리10%' limit 1), "요리10 단계 3번입니다."),
(1, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리11%' limit 1), "요리11 단계 1번입니다."),
(2, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리11%' limit 1), "요리11 단계 2번입니다."),
(3, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리11%' limit 1), "요리11 단계 3번입니다."),
(1, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리12%' limit 1), "요리12 단계 2번입니다."),
(2, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리12%' limit 1), "요리12 단계 2번입니다."),
(3, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리12%' limit 1), "요리12 단계 3번입니다."),
(1, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리13%' limit 1), "요리13 단계 1번입니다."),
(2, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리13%' limit 1), "요리13 단계 2번입니다."),
(3, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리13%' limit 1), "요리13 단계 3번입니다."),
(1, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리14%' limit 1), "요리14 단계 2번입니다."),
(2, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리14%' limit 1), "요리14 단계 2번입니다."),
(3, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리14%' limit 1), "요리14 단계 3번입니다."),
(1, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리15%' limit 1), "요리15 단계 1번입니다."),
(2, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리15%' limit 1), "요리15 단계 2번입니다."),
(3, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리15%' limit 1), "요리15 단계 3번입니다."),
(1, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리16%' limit 1), "요리16 단계 2번입니다."),
(2, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리16%' limit 1), "요리16 단계 2번입니다."),
(3, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리16%' limit 1), "요리16 단계 3번입니다."),
(1, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리17%' limit 1), "요리17 단계 1번입니다."),
(2, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리17%' limit 1), "요리17 단계 2번입니다."),
(3, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리17%' limit 1), "요리17 단계 3번입니다."),
(1, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리18%' limit 1), "요리18 단계 2번입니다."),
(2, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리18%' limit 1), "요리18 단계 2번입니다."),
(3, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리19%' limit 1), "요리18 단계 3번입니다."),
(1, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리19%' limit 1), "요리19 단계 1번입니다."),
(2, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리19%' limit 1), "요리19 단계 2번입니다."),
(3, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리19%' limit 1), "요리19 단계 3번입니다."),
(1, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리20%' limit 1), "요리20 단계 1번입니다."),
(2, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리20%' limit 1), "요리20 단계 2번입니다."),
(3, 10, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리20%' limit 1), "요리20 단계 3번입니다.");

INSERT INTO ingredient(ingre_order, recipe_id, name, qqt)
VALUES
(1, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리1%' limit 1), '감자', '2개'),
(2, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리1%' limit 1), '양파', '1/4 개'),
(3, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리1%' limit 1), '고추장', '2 큰술'),
(1, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리2%' limit 1), '감자', '세 개'),
(2, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리2%' limit 1), '소고기', '150g'),
(1, (SELECT recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리3%' limit 1), '당근', '많이'),
(2, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리3%' limit 1), '파프리카', '적당량'),
(3, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리3%' limit 1), '양송이버섯', '다량'),
(1, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리4%' limit 1), '브로콜리', '다수'),
(2, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리4%' limit 1), '마늘', '쪼끔'),
(3, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리4%' limit 1), '간장', '많은 양'),
(1, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리5%' limit 1), '양파', '1/2 개'),
(2, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리5%' limit 1), '마요네즈', '적당히'),
(3, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리5%' limit 1), '레몬즙', '1큰술'),
(1, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리6%' limit 1), '토마토', '2개'),
(2, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리6%' limit 1), '올리브오일', '마음껏'),
(3, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리6%' limit 1), '바질잎', '적당량'),
(1, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리7%' limit 1), '치즈', '많은 양'),
(2, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리7%' limit 1), '베이컨', '2줄'),
(3, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리7%' limit 1), '계란', '3개'),
(1, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리8%' limit 1), '당근', '적당량'),
(2, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리8%' limit 1), '양파', '1/2 개'),
(3, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리8%' limit 1), '감자', '4개'),
(1, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리9%' limit 1), '소고기', '200g'),
(2, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리9%' limit 1), '양배추', '적당량'),
(3, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리9%' limit 1), '당근', '1/2 개'),
(1, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리10%' limit 1), '닭가슴살', '2조각'),
(2, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리10%' limit 1), '샐러드 채소', '다양한 종류로'),
(3, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리10%' limit 1), '올리브 오일', '마음껏'),
(1, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리11%' limit 1), '연어', '200g'),
(2, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리11%' limit 1), '레몬', '1개'),
(3, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리11%' limit 1), '아보카도', '1개'),
(1, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리12%' limit 1), '김', '10장'),
(2, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리12%' limit 1), '쌀', '2컵'),
(3, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리12%' limit 1), '바다장어', '200g'),
(1, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리13%' limit 1), '스파게티면', '200g'),
(2, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리13%' limit 1), '새우', '8마리'),
(3, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리13%' limit 1), '홍고추', '1개'),
(1, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리14%' limit 1), '계란', '3개'),
(2, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리14%' limit 1), '밥', '2공기'),
(3, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리14%' limit 1), '햄', '3조각'),
(1, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리15%' limit 1), '닭고기', '300g'),
(2, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리15%' limit 1), '양파', '1개'),
(3, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리15%' limit 1), '감자', '2개'),
(1, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리16%' limit 1), '오이', '1개'),
(2, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리16%' limit 1), '당근', '1/2 개'),
(3, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리16%' limit 1), '양파', '1/4 개'),
(1, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리17%' limit 1), '가지', '1개'),
(2, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리17%' limit 1), '양파', '1/2 개'),
(3, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리17%' limit 1), '파프리카', '1/2 개'),
(1, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리18%' limit 1), '새우', '300g'),
(2, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리18%' limit 1), '마늘', '2쪽'),
(3, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리18%' limit 1), '고추', '2개'),
(1, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리19%' limit 1), '참치캔', '1캔'),
(2, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리19%' limit 1), '마요네즈', '마음껏'),
(3, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리19%' limit 1), '양파', '1/2 개'),
(1, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리20%' limit 1), '계란', '2개'),
(2, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리20%' limit 1), '우유', '100ml'),
(3, (SELECT  recipe_id FROM recipe WHERE recipe_name LIKE '%테스트요리20%' limit 1), '설탕', '2큰술');

